spring.datasource:
  master:
    jdbcUrl: jdbc:mysql://localhost:3307/sharding # master DB url
    username: epfzja
    password: Tjdgus12
  slave:
    jdbcUrl: jdbc:mysql://localhost:3308/sharding # slave DB url
    username: epfzja
    password: Tjdgus12

hibernate:
  dialect: org.hibernate.dialect.MySQLDialect
  show_sql: true
  hbm2ddl:
    auto: create
